- name: 1st conf
  hosts: all
  become: yes
  vars_files:
  - vars/variables.yml
  gather_facts: yes
  roles:
  #- update
  - docker

  - name: 2nd conf
  hosts: portainer
  become: yes
  vars_files:
  - vars/variables.yml
  gather_facts: yes
  roles:
  #- update
  #- docker
  #- netplan
  #- hostname
  - portainer

    
